/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrganizationsRouteRouteImport } from './routes/_authenticated/organizations/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardWorkspacesRouteImport } from './routes/_authenticated/dashboard/workspaces'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardOrganizationsRouteImport } from './routes/_authenticated/dashboard/organizations'
import { Route as AuthenticatedOrganizationsOrganizationIdRouteRouteImport } from './routes/_authenticated/organizations/$organizationId/route'
import { Route as AuthenticatedDashboardOrganizationsNewRouteImport } from './routes/_authenticated/dashboard/organizations_.new'
import { Route as AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteImport } from './routes/_authenticated/organizations/$organizationId/workspaces/route'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/route'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationIndexRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/index'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/settings'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationMembersRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/members'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationInviteRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/invite'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationBillingRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/billing'
import { Route as AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteImport } from './routes/_authenticated/organizations/$organizationId/workspaces/$workspaceId/route'
import { Route as AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/organizations/$organizationId/workspaces/$workspaceId/index'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/workspaces/index'
import { Route as AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRouteImport } from './routes/_authenticated/organizations/$organizationId/workspaces/$workspaceId/members'
import { Route as AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRouteImport } from './routes/_authenticated/organizations/$organizationId/_organization/workspaces/new'
import { Route as AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRouteImport } from './routes/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/index'
import { Route as AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport } from './routes/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationsRouteRoute =
  AuthenticatedOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardWorkspacesRoute =
  AuthenticatedDashboardWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrganizationsRoute =
  AuthenticatedDashboardOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdRouteRoute =
  AuthenticatedOrganizationsOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => AuthenticatedOrganizationsRouteRoute,
  } as any)
const AuthenticatedDashboardOrganizationsNewRoute =
  AuthenticatedDashboardOrganizationsNewRouteImport.update({
    id: '/organizations_/new',
    path: '/organizations/new',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRoute =
  AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedOrganizationsOrganizationIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteImport.update({
    id: '/_organization',
    getParentRoute: () => AuthenticatedOrganizationsOrganizationIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationMembersRouteImport.update(
    {
      id: '/members',
      path: '/members',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () =>
      AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationBillingRouteImport.update(
    {
      id: '/billing',
      path: '/billing',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute =
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteImport.update(
    {
      id: '/$workspaceId',
      path: '/$workspaceId',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRouteImport.update(
    {
      id: '/workspaces/',
      path: '/workspaces/',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute =
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRouteImport.update(
    {
      id: '/members',
      path: '/members',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute =
  AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRouteImport.update(
    {
      id: '/workspaces/new',
      path: '/workspaces/new',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute =
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRouteImport.update(
    {
      id: '/documents/',
      path: '/documents/',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute =
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport.update(
    {
      id: '/documents/$documentId',
      path: '/documents/$documentId',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/organizations': typeof AuthenticatedOrganizationsRouteRouteWithChildren
  '/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteWithChildren
  '/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/workspaces': typeof AuthenticatedDashboardWorkspacesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/organizations/$organizationId/workspaces': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteWithChildren
  '/dashboard/organizations/new': typeof AuthenticatedDashboardOrganizationsNewRoute
  '/organizations/$organizationId/workspaces/$workspaceId': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/organizations/$organizationId/billing': typeof AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute
  '/organizations/$organizationId/invite': typeof AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute
  '/organizations/$organizationId/members': typeof AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute
  '/organizations/$organizationId/settings': typeof AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute
  '/organizations/$organizationId/': typeof AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute
  '/organizations/$organizationId/workspaces/new': typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute
  '/organizations/$organizationId/workspaces/$workspaceId/members': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute
  '/organizations/$organizationId/workspaces/': typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute
  '/organizations/$organizationId/workspaces/$workspaceId/': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute
  '/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute
  '/organizations/$organizationId/workspaces/$workspaceId/documents/': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteRouteWithChildren
  '/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute
  '/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/workspaces': typeof AuthenticatedDashboardWorkspacesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/organizations/$organizationId/workspaces': typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute
  '/dashboard/organizations/new': typeof AuthenticatedDashboardOrganizationsNewRoute
  '/organizations/$organizationId/billing': typeof AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute
  '/organizations/$organizationId/invite': typeof AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute
  '/organizations/$organizationId/members': typeof AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute
  '/organizations/$organizationId/settings': typeof AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute
  '/organizations/$organizationId/workspaces/new': typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute
  '/organizations/$organizationId/workspaces/$workspaceId/members': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute
  '/organizations/$organizationId/workspaces/$workspaceId': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute
  '/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute
  '/organizations/$organizationId/workspaces/$workspaceId/documents': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteRouteWithChildren
  '/_authenticated/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdRouteRouteWithChildren
  '/_authenticated/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/workspaces': typeof AuthenticatedDashboardWorkspacesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/organizations/$organizationId/_organization': typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteWithChildren
  '/_authenticated/organizations/$organizationId/workspaces': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteWithChildren
  '/_authenticated/dashboard/organizations_/new': typeof AuthenticatedDashboardOrganizationsNewRoute
  '/_authenticated/organizations/$organizationId/workspaces/$workspaceId': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_authenticated/organizations/$organizationId/_organization/billing': typeof AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute
  '/_authenticated/organizations/$organizationId/_organization/invite': typeof AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute
  '/_authenticated/organizations/$organizationId/_organization/members': typeof AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute
  '/_authenticated/organizations/$organizationId/_organization/settings': typeof AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute
  '/_authenticated/organizations/$organizationId/_organization/': typeof AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute
  '/_authenticated/organizations/$organizationId/_organization/workspaces/new': typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute
  '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/members': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute
  '/_authenticated/organizations/$organizationId/_organization/workspaces/': typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute
  '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute
  '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/': typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/organizations'
    | '/organizations/$organizationId'
    | '/dashboard/organizations'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/workspaces'
    | '/dashboard/'
    | '/organizations/$organizationId/workspaces'
    | '/dashboard/organizations/new'
    | '/organizations/$organizationId/workspaces/$workspaceId'
    | '/organizations/$organizationId/billing'
    | '/organizations/$organizationId/invite'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/workspaces/new'
    | '/organizations/$organizationId/workspaces/$workspaceId/members'
    | '/organizations/$organizationId/workspaces/'
    | '/organizations/$organizationId/workspaces/$workspaceId/'
    | '/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId'
    | '/organizations/$organizationId/workspaces/$workspaceId/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/signin'
    | '/signup'
    | '/organizations'
    | '/organizations/$organizationId'
    | '/dashboard/organizations'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/workspaces'
    | '/dashboard'
    | '/organizations/$organizationId/workspaces'
    | '/dashboard/organizations/new'
    | '/organizations/$organizationId/billing'
    | '/organizations/$organizationId/invite'
    | '/organizations/$organizationId/members'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/workspaces/new'
    | '/organizations/$organizationId/workspaces/$workspaceId/members'
    | '/organizations/$organizationId/workspaces/$workspaceId'
    | '/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId'
    | '/organizations/$organizationId/workspaces/$workspaceId/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/signin'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/organizations'
    | '/_authenticated/organizations/$organizationId'
    | '/_authenticated/dashboard/organizations'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/workspaces'
    | '/_authenticated/dashboard/'
    | '/_authenticated/organizations/$organizationId/_organization'
    | '/_authenticated/organizations/$organizationId/workspaces'
    | '/_authenticated/dashboard/organizations_/new'
    | '/_authenticated/organizations/$organizationId/workspaces/$workspaceId'
    | '/_authenticated/organizations/$organizationId/_organization/billing'
    | '/_authenticated/organizations/$organizationId/_organization/invite'
    | '/_authenticated/organizations/$organizationId/_organization/members'
    | '/_authenticated/organizations/$organizationId/_organization/settings'
    | '/_authenticated/organizations/$organizationId/_organization/'
    | '/_authenticated/organizations/$organizationId/_organization/workspaces/new'
    | '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/members'
    | '/_authenticated/organizations/$organizationId/_organization/workspaces/'
    | '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/'
    | '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId'
    | '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/workspaces': {
      id: '/_authenticated/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspacesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/organizations': {
      id: '/_authenticated/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/organizations/$organizationId': {
      id: '/_authenticated/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRouteRoute
    }
    '/_authenticated/dashboard/organizations_/new': {
      id: '/_authenticated/dashboard/organizations_/new'
      path: '/organizations/new'
      fullPath: '/dashboard/organizations/new'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/organizations/$organizationId/workspaces': {
      id: '/_authenticated/organizations/$organizationId/workspaces'
      path: '/workspaces'
      fullPath: '/organizations/$organizationId/workspaces'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization': {
      id: '/_authenticated/organizations/$organizationId/_organization'
      path: ''
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/': {
      id: '/_authenticated/organizations/$organizationId/_organization/'
      path: '/'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/settings': {
      id: '/_authenticated/organizations/$organizationId/_organization/settings'
      path: '/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/members': {
      id: '/_authenticated/organizations/$organizationId/_organization/members'
      path: '/members'
      fullPath: '/organizations/$organizationId/members'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationMembersRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/invite': {
      id: '/_authenticated/organizations/$organizationId/_organization/invite'
      path: '/invite'
      fullPath: '/organizations/$organizationId/invite'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationInviteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/billing': {
      id: '/_authenticated/organizations/$organizationId/_organization/billing'
      path: '/billing'
      fullPath: '/organizations/$organizationId/billing'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationBillingRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/workspaces/$workspaceId': {
      id: '/_authenticated/organizations/$organizationId/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/organizations/$organizationId/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRoute
    }
    '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/': {
      id: '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/organizations/$organizationId/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/workspaces/': {
      id: '/_authenticated/organizations/$organizationId/_organization/workspaces/'
      path: '/workspaces'
      fullPath: '/organizations/$organizationId/workspaces/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/members': {
      id: '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/members'
      path: '/members'
      fullPath: '/organizations/$organizationId/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute
    }
    '/_authenticated/organizations/$organizationId/_organization/workspaces/new': {
      id: '/_authenticated/organizations/$organizationId/_organization/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/organizations/$organizationId/workspaces/new'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute
    }
    '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/': {
      id: '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/'
      path: '/documents'
      fullPath: '/organizations/$organizationId/workspaces/$workspaceId/documents/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute
    }
    '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId': {
      id: '/_authenticated/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/organizations/$organizationId/workspaces/$workspaceId/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardOrganizationsRoute: typeof AuthenticatedDashboardOrganizationsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardWorkspacesRoute: typeof AuthenticatedDashboardWorkspacesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardOrganizationsNewRoute: typeof AuthenticatedDashboardOrganizationsNewRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardOrganizationsRoute:
      AuthenticatedDashboardOrganizationsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardWorkspacesRoute:
      AuthenticatedDashboardWorkspacesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardOrganizationsNewRoute:
      AuthenticatedDashboardOrganizationsNewRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteChildren {
  AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute
  AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute
  AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute
  AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute
  AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute
  AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute
  AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute
}

const AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteChildren: AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationBillingRoute,
    AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationInviteRoute,
    AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationMembersRoute,
    AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationSettingsRoute,
    AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationIndexRoute,
    AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesNewRoute,
    AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationWorkspacesIndexRoute,
  }

const AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteWithChildren =
  AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteChildren {
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute
}

const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteChildren: AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute:
      AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdMembersRoute,
    AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute:
      AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdIndexRoute,
    AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute:
      AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsDocumentIdRoute,
    AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute:
      AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdDocumentsIndexRoute,
  }

const AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteWithChildren =
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteChildren {
  AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteWithChildren
}

const AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteChildren: AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRoute:
      AuthenticatedOrganizationsOrganizationIdWorkspacesWorkspaceIdRouteRouteWithChildren,
  }

const AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteWithChildren =
  AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrganizationIdRouteRouteChildren {
  AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute: typeof AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteWithChildren
  AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRoute: typeof AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteWithChildren
}

const AuthenticatedOrganizationsOrganizationIdRouteRouteChildren: AuthenticatedOrganizationsOrganizationIdRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrganizationIdOrganizationRouteRoute:
      AuthenticatedOrganizationsOrganizationIdOrganizationRouteRouteWithChildren,
    AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRoute:
      AuthenticatedOrganizationsOrganizationIdWorkspacesRouteRouteWithChildren,
  }

const AuthenticatedOrganizationsOrganizationIdRouteRouteWithChildren =
  AuthenticatedOrganizationsOrganizationIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrganizationIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationsRouteRouteChildren {
  AuthenticatedOrganizationsOrganizationIdRouteRoute: typeof AuthenticatedOrganizationsOrganizationIdRouteRouteWithChildren
}

const AuthenticatedOrganizationsRouteRouteChildren: AuthenticatedOrganizationsRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrganizationIdRouteRoute:
      AuthenticatedOrganizationsOrganizationIdRouteRouteWithChildren,
  }

const AuthenticatedOrganizationsRouteRouteWithChildren =
  AuthenticatedOrganizationsRouteRoute._addFileChildren(
    AuthenticatedOrganizationsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedOrganizationsRouteRoute: typeof AuthenticatedOrganizationsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedOrganizationsRouteRoute:
    AuthenticatedOrganizationsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
